"""Alter seeking venue column on artist table

Revision ID: 3bed3611ce5b
Revises: c9a8fa8bee38
Create Date: 2022-05-31 20:19:56.838156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bed3611ce5b'
down_revision = 'c9a8fa8bee38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(create_constraint=120), default=True))
    op.drop_column('artist', 'seeking_talent')

    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(create_constraint=120), default=True))
    op.drop_column('venue', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, default=True))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
